test: load plugin using fixture
This fixes the Node 14 import issue.
Seems like in Node 14, the cwd is not handled correctly,
causing these failures:

```sh
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
```